/**
 * Created by kiny on 16/10/22.
 */
export const REQUEST_LOGIN = 'RequestLogin';

export const SUCCESS_LOGIN = 'SuccessLogin';

export const SUCCESS_GET_AUTHORITY = 'SUCCESS_GET_AUTHORITY';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SUCCESS_GET_NEW_NOTICE = 'SUCCESS_GET_NEW_NOTICE';

export const CHAT_TO_USER = 'CHAT_TO_USER';

export const PLAY_YOU_KU_VOD = 'PLAY_YOU_KU_VOD';

export const EXIT_ROOM = 'EXIT_ROOM';

export const SUCCESS_GET_MAIN_NAV = 'SUCCESS_GET_MAIN_NAV';

export const SUCCESS_GET_CUSTOM_NAV_INFO = 'SUCCESS_GET_CUSTOM_NAV_INFO';

export const SUCCESS_GET_USER_ONLINE = 'SUCCESS_GET_USER_ONLINE';

export const SUCCESS_GET_RADMON_ROBOT = 'SUCCESS_GET_RADMON_ROBOT';

export const SUCCESS_GET_AD = 'SUCCESS_GET_AD';

export const SUCCESS_GET_BROADCAST = 'SUCCESS_GET_BROADCAST';

export const SUCCESS_GET_ROOM_INFO = 'SUCCESS_GET_ROOM_INFO';

export const SUCCESS_GET_ALL_ROOMS = 'SUCCESS_GET_ALL_ROOMS';

export const SUCCESS_GET_NO_AUTHORITY_TIPS = 'SUCCESS_GET_NO_AUTHORITY_TIPS';

export const SUCCESS_LOGIN_WITH_GUEST = 'SUCCESS_LOGIN_WITH_GUEST';

export const SUCCESS_LOGIN_CHAT_GUEST_USER = 'SUCCESS_LOGIN_CHAT_GUEST_USER';

export const SUCCESS_REFRESH_TOKEN = 'SUCCESS_REFRESH_TOKEN';

export const SUCCESS_ONLINE_CHECK = 'SUCCESS_ONLINE_CHECk';
